baseURL = 'https://now.blackpiratex.com/'
languageCode = 'en-us'
title = 'Now'
theme = 'mini-nc'


[imaging]
  anchor = 'Smart'
  bgColor = '#ffffff'
  hint = 'photo'
  quality = 10
  resampleFilter = 'Box'

  [imaging.exif]
    disableDate = true
    disableLatLong = true
    excludeFields = ''
    includeFields = ''


[params]
  author = 'BlackPirateX'
  description = "Brief thoughts — posted as they happen."
  tags = 'tags'
  catagories = 'catagories'


[outputFormats.SearchIndex]
mediaType = "application/json"
baseName = "searchindex"
isPlainText = true
notAlternative = true

[outputs]
home = [ "HTML", "RSS", "SearchIndex", "JSON"]

# In your config.toml file

[archives]
  enabled = true
