# .github/workflows/mastodon.yml

name: Trigger Mastodon Post

on:
  # Trigger on pushes to the main branch
  push:
    branches:
      - master # Or master, or your main production branch

jobs:
  trigger_mastodon_post:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 1 minute for deployment to settle
        run: sleep 60
        shell: bash

      - name: Trigger Post to Mastodon Function
        env:
          VERCEL_URL: ${{ secrets.VERCEL_PRODUCTION_URL }}
        run: |
          echo "Pinging URL: $VERCEL_URL/api/post-to-mastodon"
          curl --fail -X GET "$VERCEL_URL/api/post-to-mastodon"
        shell: bash
